# -*- coding: utf-8 -*-
"""toy_project_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aw854sHD8A63FZbsGkeol8IBXmSro6Oc

# **0. Preprocessing + EDA + Feature selection**

## for uploading file from local machine to cloud server
"""

from google.colab import files

# Upload file from your desktop
uploaded = files.upload()

import pandas as pd

pd.read_csv("/content/placement.csv")

import numpy as np
import pandas as pd
df=pd.read_csv("/content/placement.csv")

df.head()

df.shape # shape is a attribute of numpy class . so, it does not required brackets.

df.info()

df=df.iloc[:,1:] # [rows range , columns range]

df.head()

import matplotlib.pyplot as plt

plt.scatter(df["cgpa"],df["iq"],c=df["placement"])
#cgpa in x-axis and iq in y=axis and color = placement.

"""# **1. Extract input and output columns**"""

x=df.iloc[:,0:2]# independent variable(iq,cgpa)
y=df.iloc[:,-1]# dependent variable(placement)

y,x

"""# **3. Train Test Split (Cross Validation)**
Sometimes train the model process also in include in ML.

A package is a collection of modules, while a library is a collection of packages.

**scikit-learn/sklearn = library**

**Train Test Split after scaling**

sklearn.model_selection = package ,  train_test_split = class
"""

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)
#0.1 means 90% data will go to train and 10% data will go test randomaly.

"""# **2. Scale the values**
this process include first according to numering

sklearn.preprocessing = package ,  StandardScaler = class , scaler = object
"""

from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()# creating object of StandardScaler() function which has the power call every functions present in standardscaler

x_train=scaler.fit_transform(x_train) #scale data from -1 to 1

x_test=scaler.transform(x_test)# dont require fit cause it already reconize thepattern of data.

"""# **4. Evaluate the model / model selection**

sklearn.linear_model = package ,  LogisticRegression = class , clf = object
"""

from sklearn.linear_model import LogisticRegression

clf= LogisticRegression()

clf.fit(x_train,y_train) #model training

y_pred=clf.predict(x_test) # x_test contain 10% data whose y_test value is hidden.

y_test

"""sklearn.metrics = package ,  accuracy_score = class"""

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred) # checking accuracy . 90% data is accurate.

"""**Decision Bondary = ML model notices patterns in our model (visualize)**
**mlxtend = library**

mlxtend.plotting = package ,  plot_decision_regions = class
"""

import mlxtend # Import the installed package

print(mlxtend.__version__) # Check the version if the package is installed correctly

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(x_train,y_train.values,clf=clf,legend=2)

"""# **5. Deploy the model**"""

import pickle

pickle.dump(clf,open('model.pkl','wb'))